version: '3'

services:
  nodejs:
    image: posts_api
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:6.0.11-ubi8
    ports:
      - "27017:27017"
